Parsing stages for nested canonical links
osrf/sdf_tutorials pull request #40
Opened 2020-09-02 05:02 UTC by scpeters

Add parsing stage for identifying the canonical
link of a model with 3 steps:

1. If //model/@canonical_link is specified, choose that link.
2. If //model/@canonical_link is not specified, and the model
   has at least one link, choose the first link.
3. Otherwise, chose the canonical link of the first nested
   model. This may be a recursive process if there are multiple
   levels of nested models without links.

2020-09-02 05:04 UTC, scpeters commented
this should complete https://github.com/osrf/sdformat/issues/342

2020-09-02 21:50 UTC, azeey requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/40)* status: all files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI, @iche033, and @scpeters)

___
*[pose_frame_semantics/proposal.md, line 1651 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/40#-MGFkpoa7AhAxxTOLpv3:-MGFkpoa7AhAxxTOLpv4:b58gjyj) ([raw file](https://github.com/osrf/sdf_tutorials/blob/fda89cfef3a38482b01b71b18956bce1c35f9e9e/pose_frame_semantics/proposal.md#L1651)):*
> ```Markdown
>     7.2 Identify the canonical link of the model:
> 
>     7.2.1 Return an error for 
> ```

Not sure the first 7.2.1 supposed to be there
___
*[pose_frame_semantics/proposal.md, line 1660 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/40#-MGFlOL-4Agdx2HSDq2h:-MGFlOL-4Agdx2HSDq2i:budolml) ([raw file](https://github.com/osrf/sdf_tutorials/blob/fda89cfef3a38482b01b71b18956bce1c35f9e9e/pose_frame_semantics/proposal.md#L1660)):*
> ```Markdown
>           contains links, choose the first link.
> 
>     7.2.3 Otherwise (i.e. if the `//model/@canonical_link` attribute
> ```

7.2.2 and 7.2.3 look the same to me.  Should this be about nested models?


<!-- Sent from Reviewable.io -->

2020-09-03 17:20 UTC, EricCousineau-TRI approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> with some minor comments

> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/40#-:-MGJyzFy-x3CrkIoOP8W:b-v72ds0)* status: all files reviewed, 2 unresolved discussions (waiting on @azeey, @iche033, and @scpeters)

___
*[pose_frame_semantics/proposal.md, line 1660 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/40#-MGFlOL-4Agdx2HSDq2h:-MGJyk0D2sd6g_luq7n6:b-b58ei2) ([raw file](https://github.com/osrf/sdf_tutorials/blob/fda89cfef3a38482b01b71b18956bce1c35f9e9e/pose_frame_semantics/proposal.md#L1660)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

7.2.2 and 7.2.3 look the same to me.  Should this be about nested models?
</blockquote></details>

Perhaps they could be folded by saying something like
"... by choosing the first link. If there is no link directly in the current model, then proceed to use the next nested model's canonical link, recursing until a link is found, otherwise returning an error."


<!-- Sent from Reviewable.io -->

2020-09-18 08:26 UTC, scpeters reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/40)* status: all files reviewed, 2 unresolved discussions (waiting on @azeey and @iche033)

___
*[pose_frame_semantics/proposal.md, line 1651 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/40#-MGFkpoa7AhAxxTOLpv3:-MHVJHUb7wWKuraGztNW:bommbrh) ([raw file](https://github.com/osrf/sdf_tutorials/blob/fda89cfef3a38482b01b71b18956bce1c35f9e9e/pose_frame_semantics/proposal.md#L1651)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Not sure the first 7.2.1 supposed to be there
</blockquote></details>

it was incomplete; I meant for that step to mean to quickly throw an error if the model has no links or nested models; updated in 2bc6370bf998b43adbbf26396a29b8028237832a
___
*[pose_frame_semantics/proposal.md, line 1660 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/40#-MGFlOL-4Agdx2HSDq2h:-MHVJQVkCFemr4dGRBk5:b-ll1saf) ([raw file](https://github.com/osrf/sdf_tutorials/blob/fda89cfef3a38482b01b71b18956bce1c35f9e9e/pose_frame_semantics/proposal.md#L1660)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Perhaps they could be folded by saying something like
"... by choosing the first link. If there is no link directly in the current model, then proceed to use the next nested model's canonical link, recursing until a link is found, otherwise returning an error."
</blockquote></details>

I've updated it in 2bc6370bf998b43adbbf26396a29b8028237832a to fix the numbering and explain how to look into nested models if the current model has no links


<!-- Sent from Reviewable.io -->

2020-09-22 15:55 UTC, scpeters commented
@azeey can you take a look at my recent fixes to this PR?

2020-09-24 17:58 UTC, azeey approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/40#-:-MI0FyUx055ayNONi8aB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @iche033)



<!-- Sent from Reviewable.io -->

2020-09-24 18:04 UTC, merged