composition: Add section for up-converting unflattened models
osrf/sdf_tutorials pull request #41
Opened 2020-09-10 20:31 UTC by EricCousineau-TRI

As motivated here: https://github.com/osrf/sdformat/pull/355#pullrequestreview-486246061
Towards osrf/sdformat#342
Resolves #39

Preview:
http://sdformat.org/tutorials?tut=composition_proposal&branch=feature-sdformat-pr355-up-convert&repo=https%3A%2F%2Fgithub.com%2FEricCousineau-TRI%2Fsdf_tutorials-1#1-4-7-up-converting-flattened-models

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/osrf/sdf_tutorials/41)

2020-09-17 17:51 UTC, scpeters requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/41)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[composition/proposal.md, line 61 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MHS6Lv1243SjexRJ2lL:-MHS6Lv1243SjexRJ2lM:b8cuh4k) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3cb532f463f3293640c74555a1e9a5fba957c8af/composition/proposal.md#L61)):*
> ```Markdown
> behavior than direct nesting with `//model/model`,
> part of the reason being that nesting directly with `//model/model` was not
> implemented in the `libsdformat` until 9.3.0. As mentioned in the
> ```

nit: `in the libsdformat` -> `in libsdformat`
___
*[composition/proposal.md, line 64 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MHS6fkG6g6jTn0bF_Xe:-MHS6fkG6g6jTn0bF_Xf:b-8frkfb) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3cb532f463f3293640c74555a1e9a5fba957c8af/composition/proposal.md#L64)):*
> ```Markdown
> [Legacy Behavior](/tutorials?tut=composition&ver=1.5&#libsdformats-implementation-of-include-in-models) documentation, `//include` works by effectively flattening the model; when this happens, certain details may "leak" through.
> 
> Normall, nesting of models generally implies that the elements can be
> ```

Normally
___
*[composition/proposal.md, line 583 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MHS7PaW3J7Prq6IrF5F:-MHS7PaW3J7Prq6IrF5G:b-cyri4u) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3cb532f463f3293640c74555a1e9a5fba957c8af/composition/proposal.md#L583)):*
> ```Markdown
> `M1::my_link`) should be "unnested" (e.g. `my_link` in model `M1`).
> 
> To illustrate, the following model from the Legacy Behavior documentation:
> ```

add hyperlink? http://sdformat.org/tutorials?tut=composition&cat=specification&#libsdformats-implementation-of-include-in-models
___
*[composition/proposal.md, line 597 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MHS82MK0KwpixEQBd4f:-MHS82MK0KwpixEQBd4g:b9t49hl) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3cb532f463f3293640c74555a1e9a5fba957c8af/composition/proposal.md#L597)):*
> ```Markdown
>       </visual>
>     </link>
>     <link name="ChildModel::L2"/>
> ```

I think the example in the legacy behavior documentation may be wrong; I think this link would have a pose of `1 0 1 0 0 0`
___
*[composition/proposal.md, line 662 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MHSAXLrB-jzoFhrLPLX:-MHSAXLrB-jzoFhrLPLY:b-of9a91) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3cb532f463f3293640c74555a1e9a5fba957c8af/composition/proposal.md#L662)):*
> ```Markdown
> * Since the naively converted file is neither SDFormat 1.5 nor 1.8, it is
> indicated as SDFormat `1.5*`, meaning that it's an intermediate format which
> namely adheres to SDFormat 1.5, but has directly nested models.
> ```

SDFormat 1.5 supports directly nested models in the spec, so I think we could leave it as `1.5`
___
*[composition/proposal.md, line 665 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MHSAhZY8kn-_tRDgAB2:-MHSAhZY8kn-_tRDgAB3:bac86gj) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3cb532f463f3293640c74555a1e9a5fba957c8af/composition/proposal.md#L665)):*
> ```Markdown
> * Since `libsdformat9.3` supported direct nesting but `//include` still
> worked via flattening, unflattening will occur regardless of whether or not
> there are directly nested models in the model, and the unflattening my handle
> ```

`my` -> `may`
___
*[composition/proposal.md, line 670 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MHSAvjADYK_mKpYp9zM:-MHSAvjADYK_mKpYp9zN:b9kqp8p) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3cb532f463f3293640c74555a1e9a5fba957c8af/composition/proposal.md#L670)):*
> ```Markdown
> the newly created `//model/pose`.
>   * This offers simplicity and ensures that the effective `__model__` frame
>   will coincide with the newly created nested models' `__model__` frames.
> ```

as of `libsdformat 9.2`, the a flattened model would also have an injected `ChildModel::__model__` per [bitbucket pr 668](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/pull-requests/668/page/1); perhaps we need to upgrade the legacy behavior documentation a bit; this reasoning is valid for versions < 9.2 but doesn't cover the injected `__model__` frames


<!-- Sent from Reviewable.io -->

2020-09-24 17:52 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/41)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[composition/proposal.md, line 61 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MHS6Lv1243SjexRJ2lL:-MI0EWVC4rUiKdmJTfjM:b-896fix) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3cb532f463f3293640c74555a1e9a5fba957c8af/composition/proposal.md#L61)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

nit: `in the libsdformat` -> `in libsdformat`
</blockquote></details>

Done.
___
*[composition/proposal.md, line 64 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MHS6fkG6g6jTn0bF_Xe:-MI0EXZY908TxqYDgyOP:b-896fix) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3cb532f463f3293640c74555a1e9a5fba957c8af/composition/proposal.md#L64)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

Normally
</blockquote></details>

Done.
___
*[composition/proposal.md, line 583 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MHS7PaW3J7Prq6IrF5F:-MI0EXtHDIPXDVgh-xOV:b-896fix) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3cb532f463f3293640c74555a1e9a5fba957c8af/composition/proposal.md#L583)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

add hyperlink? http://sdformat.org/tutorials?tut=composition&cat=specification&#libsdformats-implementation-of-include-in-models
</blockquote></details>

Done.
___
*[composition/proposal.md, line 597 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MHS82MK0KwpixEQBd4f:-MI0EYol8XoGU5yEIlp4:b-376vyo) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3cb532f463f3293640c74555a1e9a5fba957c8af/composition/proposal.md#L597)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

I think the example in the legacy behavior documentation may be wrong; I think this link would have a pose of `1 0 1 0 0 0`
</blockquote></details>

Done. Good catch!
___
*[composition/proposal.md, line 662 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MHSAXLrB-jzoFhrLPLX:-MI0E_1D6SouvJ_8pWWu:bxrw1z4) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3cb532f463f3293640c74555a1e9a5fba957c8af/composition/proposal.md#L662)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

SDFormat 1.5 supports directly nested models in the spec, so I think we could leave it as `1.5`
</blockquote></details>

Done. I actually changed it to 1.4; if we think we won't run into this in the wild, then I could strip it out entirely.
___
*[composition/proposal.md, line 665 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MHSAhZY8kn-_tRDgAB2:-MI0EdMxCeI1ZeM6nS3O:b-896fix) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3cb532f463f3293640c74555a1e9a5fba957c8af/composition/proposal.md#L665)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

`my` -> `may`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-24 18:24 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/41)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[composition/proposal.md, line 680 at r3](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MI0LOA4EslK-hQYlJNb:-MI0LOA4EslK-hQYlJNc:b-w8zrkg) ([raw file](https://github.com/osrf/sdf_tutorials/blob/42c7774ed29ed8b07c7e7962e28c0bbd902d8998/composition/proposal.md#L680)):*
> ```Markdown
>   will coincide with the newly created nested models' `__model__` frames.
> 
> **Example of a failing conversions**
> ```

Working: Should also try to explicitly state where this happens in high or low level parsing stages.

- readDoc - may handle the conversion, then pass off to readXml
- readXml - should handle the latest version


<!-- Sent from Reviewable.io -->

2020-09-24 18:24 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/41)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[composition/proposal.md, line 670 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MHSAvjADYK_mKpYp9zM:-MI0LwgJ8S7Okv_9bkRJ:b-b8jaoe) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3cb532f463f3293640c74555a1e9a5fba957c8af/composition/proposal.md#L670)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

as of `libsdformat 9.2`, the a flattened model would also have an injected `ChildModel::__model__` per [bitbucket pr 668](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/pull-requests/668/page/1); perhaps we need to upgrade the legacy behavior documentation a bit; this reasoning is valid for versions < 9.2 but doesn't cover the injected `__model__` frames
</blockquote></details>

Working: Will update examples (legacy and here) that incorporate the `__model__` frames.


<!-- Sent from Reviewable.io -->

2020-09-24 18:44 UTC, scpeters reviewed
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/41)* status: all files reviewed, 2 unresolved discussions (waiting on @azeey and @EricCousineau-TRI)



<!-- Sent from Reviewable.io -->

2020-09-24 19:55 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/41)* status: all files reviewed, 2 unresolved discussions (waiting on @azeey and @EricCousineau-TRI)

___
*[composition/proposal.md, line 670 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MHSAvjADYK_mKpYp9zM:-MI0fojIDjKxhLDeHJN_:b-6fllve) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3cb532f463f3293640c74555a1e9a5fba957c8af/composition/proposal.md#L670)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Will update examples (legacy and here) that incorporate the `__model__` frames.
</blockquote></details>

Will first confirm what happens with `SDFormat 1.4` and include.


<!-- Sent from Reviewable.io -->

2020-09-24 19:56 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/41)* status: all files reviewed, 2 unresolved discussions (waiting on @azeey and @EricCousineau-TRI)

___
*[composition/proposal.md, line 670 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MHSAvjADYK_mKpYp9zM:-MI0fyeMA1DhBAdGXHk3:b-7lj3wp) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3cb532f463f3293640c74555a1e9a5fba957c8af/composition/proposal.md#L670)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Will first confirm what happens with `SDFormat 1.4` and include.
</blockquote></details>

Will modified tests introduced here:
https://github.com/osrf/sdformat/compare/cc1f9b00e31b991a71343db5afbe3665d8af1ff8..4836e3d2577fe4e7fe52a94805bc8a9ba6bb432d


<!-- Sent from Reviewable.io -->

2020-09-24 20:28 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/41)* status: all files reviewed, 2 unresolved discussions (waiting on @azeey and @EricCousineau-TRI)

___
*[composition/proposal.md, line 670 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MHSAvjADYK_mKpYp9zM:-MI0n8J9C34BiVbcAgbl:b7cjofq) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3cb532f463f3293640c74555a1e9a5fba957c8af/composition/proposal.md#L670)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Will modified tests introduced here:
https://github.com/osrf/sdformat/compare/cc1f9b00e31b991a71343db5afbe3665d8af1ff8..4836e3d2577fe4e7fe52a94805bc8a9ba6bb432d
</blockquote></details>

Setup:

Using this workspace setup: https://github.com/EricCousineau-TRI/repro/commit/0162a3d7e38196a36207738bb3137dde4610b7fc
```
colcon build
cd build/sdformat11
make INTEGRATION_nested_model  # For intermediate changes.
./test/integration/INTEGRATION_nested_model --gtest_filter=NestedModel.NestedModelWithFramesDirectComparison
```


<!-- Sent from Reviewable.io -->

2020-09-24 20:42 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/41)* status: all files reviewed, 2 unresolved discussions (waiting on @azeey and @EricCousineau-TRI)

___
*[composition/proposal.md, line 670 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MHSAvjADYK_mKpYp9zM:-MI0qHLx9Ii321ZxOCaV:b-2k56uz) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3cb532f463f3293640c74555a1e9a5fba957c8af/composition/proposal.md#L670)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Setup:

Using this workspace setup: https://github.com/EricCousineau-TRI/repro/commit/0162a3d7e38196a36207738bb3137dde4610b7fc
```
colcon build
cd build/sdformat11
make INTEGRATION_nested_model  # For intermediate changes.
./test/integration/INTEGRATION_nested_model --gtest_filter=NestedModel.NestedModelWithFramesDirectComparison
```
</blockquote></details>

With this branch: https://github.com/osrf/sdformat/compare/master...EricCousineau-TRI:feature-composition-model-inject-wip | osrf/sdformat@3f46da9

Some minor notes (related to above) discussion - but setting `/sdf/@version="1.4"` doesn't seem to trip anything up in the parsing setup.
Makes senese, just wanted to confirm.


<!-- Sent from Reviewable.io -->

2020-09-24 20:48 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/41)* status: all files reviewed, 2 unresolved discussions (waiting on @azeey and @EricCousineau-TRI)

___
*[composition/proposal.md, line 670 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MHSAvjADYK_mKpYp9zM:-MI0runF1llDP6Nfr7dJ:b-83bomy) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3cb532f463f3293640c74555a1e9a5fba957c8af/composition/proposal.md#L670)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

With this branch: https://github.com/osrf/sdformat/compare/master...EricCousineau-TRI:feature-composition-model-inject-wip | osrf/sdformat@3f46da9

Some minor notes (related to above) discussion - but setting `/sdf/@version="1.4"` doesn't seem to trip anything up in the parsing setup.
Makes senese, just wanted to confirm.
</blockquote></details>

Here's what the flattened model looks like with SDFormat 1.8 (assuming it'll be the same for SDFormat 1.7):

osrf/sdformat@56d076d2


<!-- Sent from Reviewable.io -->

2020-09-24 21:08 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/41)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[composition/legacy_behavior.md, line 223 at r4](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MI0wGR82i2_kQJcpJbM:-MI0wGR82i2_kQJcpJbN:bk29rln) ([raw file](https://github.com/osrf/sdf_tutorials/blob/b3f9bf9ccbb5dfddc867da60b90dcb408268898f/composition/legacy_behavior.md#L223)):*
> ```Markdown
> 
> ```xml
> <model name="ParentModel">
> ```

BTW I've replaced this with the output of current `libsdformat`, but with some excess default values trimmed.
___
*[composition/proposal.md, line 670 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MHSAvjADYK_mKpYp9zM:-MI0wZYt818yv_eikHSk:b-896fix) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3cb532f463f3293640c74555a1e9a5fba957c8af/composition/proposal.md#L670)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Here's what the flattened model looks like with SDFormat 1.8 (assuming it'll be the same for SDFormat 1.7):

osrf/sdformat@56d076d2
</blockquote></details>

Done.
___
*[composition/proposal.md, line 668 at r3](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MI0wRoIElAnbogq2SIq:-MI0wRoIElAnbogq2SIr:b-n7xl0u) ([raw file](https://github.com/osrf/sdf_tutorials/blob/42c7774ed29ed8b07c7e7962e28c0bbd902d8998/composition/proposal.md#L668)):*
> ```Markdown
> been emitted by `libsdformat10` by using *valid* `//include` statements. It is possible to write valid models in SDFormat 1.7 that are invalid in SDFormat
> 1.8; no effort will be made to reconcile those models (see examples below).
> * Since the naively converted file is neither SDFormat 1.5 nor 1.8, it is
> ```

BTW I've removed this section for now. Per mention below, the whole "is the version tag strictly true" seems like a separate concern.


<!-- Sent from Reviewable.io -->

2020-09-24 22:24 UTC, scpeters requested changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/41)* status: all files reviewed, 2 unresolved discussions (waiting on @azeey and @EricCousineau-TRI)

___
*[composition/legacy_behavior.md, line 223 at r4](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MI0wGR82i2_kQJcpJbM:-MI1BBEz20W69MIUeYg-:bvfe4a6) ([raw file](https://github.com/osrf/sdf_tutorials/blob/b3f9bf9ccbb5dfddc867da60b90dcb408268898f/composition/legacy_behavior.md#L223)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW I've replaced this with the output of current `libsdformat`, but with some excess default values trimmed.
</blockquote></details>

looks good. How do you feel about adding a duplicate versioned 1.7 file with these changes and leaving the old version in a separate file? I can do the grunt work
___
*[composition/proposal.md, line 679 at r4](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MI1BuPX-usWpOiUUSqN:-MI1BuPX-usWpOiUUSqO:bb8u3jx) ([raw file](https://github.com/osrf/sdf_tutorials/blob/b3f9bf9ccbb5dfddc867da60b90dcb408268898f/composition/proposal.md#L679)):*
> ```Markdown
> `ChildModel::__model__`) will have this frame removed, and this will be
> converted to the appropriate `//model/pose`. If `@attached_to` is specified to
> something other than this nexted model's first link, then
> ```

nexted -> nested


<!-- Sent from Reviewable.io -->

2020-09-25 14:11 UTC, azeey approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> With minor comments

> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-:-MI4aQRH-72YBN_KH8Dw:b27131m)* status: all files reviewed, 3 unresolved discussions (waiting on @azeey and @EricCousineau-TRI)

___
*[composition/proposal.md, line 680 at r3](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MI0LOA4EslK-hQYlJNb:-MI4Zjsl2lbmfrYk5oDs:b-75gs1x) ([raw file](https://github.com/osrf/sdf_tutorials/blob/42c7774ed29ed8b07c7e7962e28c0bbd902d8998/composition/proposal.md#L680)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Should also try to explicitly state where this happens in high or low level parsing stages.

- readDoc - may handle the conversion, then pass off to readXml
- readXml - should handle the latest version
</blockquote></details>

Working: What if we create a new conversion keyword "unnest" and do it in the `Convert` class? This would only be done in a `1.7->1.8` conversion.
___
*[composition/proposal.md, line 670 at r4](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MI4XdLz1ihSucAMz0SN:-MI4XdM-0vsrMv0k0UB5:b-o3pwah) ([raw file](https://github.com/osrf/sdf_tutorials/blob/b3f9bf9ccbb5dfddc867da60b90dcb408268898f/composition/proposal.md#L670)):*
> ```Markdown
> the naive up-conversion process.
> * This up-conversion is *only* intended to support models that *could* have
> been emitted by `libsdformat10` by using *valid* `//include` statements. It is possible to write valid models in SDFormat 1.7 that are invalid in SDFormat
> ```

nit: `libsdformat10` -> `libsdformat9.3`?


<!-- Sent from Reviewable.io -->

2020-09-25 17:24 UTC, scpeters reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/41)* status: all files reviewed, 3 unresolved discussions (waiting on @azeey and @EricCousineau-TRI)

___
*[composition/proposal.md, line 680 at r3](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MI0LOA4EslK-hQYlJNb:-MI5HhqxAxgJvYwnZGa8:bwioq3g) ([raw file](https://github.com/osrf/sdf_tutorials/blob/42c7774ed29ed8b07c7e7962e28c0bbd902d8998/composition/proposal.md#L680)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Working: What if we create a new conversion keyword "unnest" and do it in the `Convert` class? This would only be done in a `1.7->1.8` conversion.
</blockquote></details>

that makes sense to me
___
*[composition/proposal.md, line 670 at r4](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MI4XdLz1ihSucAMz0SN:-MI5Cb0b6DuaAijhkpzH:bypowka) ([raw file](https://github.com/osrf/sdf_tutorials/blob/b3f9bf9ccbb5dfddc867da60b90dcb408268898f/composition/proposal.md#L670)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

nit: `libsdformat10` -> `libsdformat9.3`?
</blockquote></details>

flattening has been happening since before [libsdformat4](https://github.com/osrf/sdformat/blob/sdformat4_4.0.0/src/parser.cc#L738) and its behavior changed in [libsdformat 9.2](https://github.com/osrf/sdformat/blob/master/Changelog.md#libsdformat-920-2020-04-02) with the inclusion of [bitbucket PR 668](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/pull-requests/668/page/1). maybe we could just omit the version and say `libsdformat`?


<!-- Sent from Reviewable.io -->

2020-10-01 17:38 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/41)* status: all files reviewed, 3 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[composition/proposal.md, line 670 at r4](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MI4XdLz1ihSucAMz0SN:-MI_EcIA-zAB3GhX663i:b-qiv9qk) ([raw file](https://github.com/osrf/sdf_tutorials/blob/b3f9bf9ccbb5dfddc867da60b90dcb408268898f/composition/proposal.md#L670)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

flattening has been happening since before [libsdformat4](https://github.com/osrf/sdformat/blob/sdformat4_4.0.0/src/parser.cc#L738) and its behavior changed in [libsdformat 9.2](https://github.com/osrf/sdformat/blob/master/Changelog.md#libsdformat-920-2020-04-02) with the inclusion of [bitbucket PR 668](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/pull-requests/668/page/1). maybe we could just omit the version and say `libsdformat`?
</blockquote></details>

Actually, this bit of history seems useful. Will incorporate it here.


<!-- Sent from Reviewable.io -->

2020-10-01 17:48 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/41)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[composition/proposal.md, line 680 at r3](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MI0LOA4EslK-hQYlJNb:-MI_GNup-KhQRXAphrwi:b-tv51xy) ([raw file](https://github.com/osrf/sdf_tutorials/blob/42c7774ed29ed8b07c7e7962e28c0bbd902d8998/composition/proposal.md#L680)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

that makes sense to me
</blockquote></details>

Er, not sure what "conversion keyword" means. Can you point to that context?
___
*[composition/proposal.md, line 670 at r4](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MI4XdLz1ihSucAMz0SN:-MI_Fe4F0i6lsipd3r1z:b-hwcvye) ([raw file](https://github.com/osrf/sdf_tutorials/blob/b3f9bf9ccbb5dfddc867da60b90dcb408268898f/composition/proposal.md#L670)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Actually, this bit of history seems useful. Will incorporate it here.
</blockquote></details>

Done. Incorporated `libsdformat4`.

However, I don't think the inclusion of pose frame semantics matters in this exact bullet point. Yes, the below model does use pose frame semantics, but an invalid model could also arise from an invalid specification of other interface elements, e.g. `//joint/child`, `//join/parent`, etc.

I've updated the example below to use pre-pose-frame semantics stuff  as a better illustration.
___
*[composition/proposal.md, line 679 at r4](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MI1BuPX-usWpOiUUSqN:-MI_GJkp-h5SdTilEDQ9:b-qsx7uj) ([raw file](https://github.com/osrf/sdf_tutorials/blob/b3f9bf9ccbb5dfddc867da60b90dcb408268898f/composition/proposal.md#L679)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

nexted -> nested
</blockquote></details>

Done. Oops!


<!-- Sent from Reviewable.io -->

2020-10-01 17:49 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/41)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @scpeters)

___
*[composition/proposal.md, line 680 at r3](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MI0LOA4EslK-hQYlJNb:-MI_H4oc8Vz5UuEc0CFR:b-rkp6tr) ([raw file](https://github.com/osrf/sdf_tutorials/blob/42c7774ed29ed8b07c7e7962e28c0bbd902d8998/composition/proposal.md#L680)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Er, not sure what "conversion keyword" means. Can you point to that context?
</blockquote></details>

Yeah, also not sure what the gain is there? Can talk more f2f.


<!-- Sent from Reviewable.io -->

2020-10-01 18:55 UTC, EricCousineau-TRI commented
Per f2f:

* EC: Conversion keywords for unnesting?
    * AT: Add it to the conversion schema, like `<unnest/>` or something

e.g. [code](https://github.com/osrf/sdformat/blob/master/sdf/1.7/1_6.convert)

2020-10-01 19:34 UTC, scpeters approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/41)* status: all files reviewed, 2 unresolved discussions (waiting on @azeey and @EricCousineau-TRI)

___
*[composition/proposal.md, line 680 at r3](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MI0LOA4EslK-hQYlJNb:-MI_ddvbEUJ_68W2B_5k:bmk7n7x) ([raw file](https://github.com/osrf/sdf_tutorials/blob/42c7774ed29ed8b07c7e7962e28c0bbd902d8998/composition/proposal.md#L680)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Yeah, also not sure what the gain is there? Can talk more f2f.
</blockquote></details>

I think we agreed on this during f2f today. Does this idea require any text changes here?
___
*[composition/proposal.md, line 83 at r6](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MI_d8IF-AfMIFrN1etr:-MI_d8IF-AfMIFrN1ets:b7e7kdr) ([raw file](https://github.com/osrf/sdf_tutorials/blob/7f75d0675da38eb672f3563ea6e9bfbb6acfaf1d/composition/proposal.md#L83)):*
> ```Markdown
> legacy format. Generally, the interface between models only really needs access
> to explicit and implicit frames (for welding joints, attaching sensors, etc.).
> The present implementation of `//include` (present
> ```

nit: using "present" twice so closely sounds funny.
* "The current implementation"
or
* remove "present" from the parenthetical "(since `libsdformat4)"


<!-- Sent from Reviewable.io -->

2020-10-01 21:42 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/41)* status: all files reviewed, 2 unresolved discussions (waiting on @azeey and @EricCousineau-TRI)

___
*[composition/proposal.md, line 680 at r3](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MI0LOA4EslK-hQYlJNb:-MIa6LxI9e6SIAObFtQs:b-q0gtva) ([raw file](https://github.com/osrf/sdf_tutorials/blob/42c7774ed29ed8b07c7e7962e28c0bbd902d8998/composition/proposal.md#L680)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

I think we agreed on this during f2f today. Does this idea require any text changes here?
</blockquote></details>

Yeah, will add a brief blurb above about the potential implementation.


<!-- Sent from Reviewable.io -->

2020-10-01 21:43 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/41)* status: all files reviewed, 2 unresolved discussions (waiting on @azeey and @EricCousineau-TRI)

___
*[composition/legacy_behavior.md, line 223 at r4](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MI0wGR82i2_kQJcpJbM:-MIa6Vn_EEDzKWsvtRqE:bh9c7a4) ([raw file](https://github.com/osrf/sdf_tutorials/blob/b3f9bf9ccbb5dfddc867da60b90dcb408268898f/composition/legacy_behavior.md#L223)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

looks good. How do you feel about adding a duplicate versioned 1.7 file with these changes and leaving the old version in a separate file? I can do the grunt work
</blockquote></details>

OK Sounds good to me! I'm assuming that'll happen in a separate PR, so will get this 'un merged in.


<!-- Sent from Reviewable.io -->

2020-10-01 21:49 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/41)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @azeey and @scpeters)

___
*[composition/proposal.md, line 680 at r3](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MI0LOA4EslK-hQYlJNb:-MIa7zpg4yJC8YNvuRME:b-esxh2q) ([raw file](https://github.com/osrf/sdf_tutorials/blob/42c7774ed29ed8b07c7e7962e28c0bbd902d8998/composition/proposal.md#L680)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Yeah, will add a brief blurb above about the potential implementation.
</blockquote></details>

Done. Added in Addisu's suggestion; we can change later if it becomes different.
___
*[composition/proposal.md, line 83 at r6](https://reviewable.io/reviews/osrf/sdf_tutorials/41#-MI_d8IF-AfMIFrN1etr:-MIa8-Ud6dDpjOTgGMh3:b-896fix) ([raw file](https://github.com/osrf/sdf_tutorials/blob/7f75d0675da38eb672f3563ea6e9bfbb6acfaf1d/composition/proposal.md#L83)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

nit: using "present" twice so closely sounds funny.
* "The current implementation"
or
* remove "present" from the parenthetical "(since `libsdformat4)"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-01 22:41 UTC, merged